import streamlit as st
from groq import Groq
from datetime import datetime
from fpdf import FPDF

st.set_page_config(page_title="TEFL Grader Pro", page_icon="📝", layout="centered")

st.markdown("""
<style>
.stButton>button {background:#111;color:white;border-radius:10px;height:45px;font-weight:bold;width:100%;}
</style>
""", unsafe_allow_html=True)

if "uses" not in st.session_state:
    st.session_state.uses = 0

st.title("📝 TEFL Essay Grader Pro")
st.caption("CEFR grading in 5 seconds • Built for TEFL Teachers")

with st.expander("📘 What do the levels mean? (A1 to C2)", expanded=False):
    st.markdown("""
    **A1 - Beginner:** Simple phrases
    **A2 - Elementary:** Daily routines
    **B1 - Intermediate:** Connected paragraphs
    **B2 - Upper-Intermediate:** Clear argument
    **C1 - Advanced:** Complex, well-structured
    **C2 - Mastery:** Near-native
    """)

essay = st.text_area("Paste Student Essay:", height=200, placeholder="I go to market yesterday...")
level = st.selectbox("Target Level:", ["A1","A2","B1","B2","C1","C2"])

def clean(text):
    if not text:
        return ""
    return text.replace('“','"').replace('”','"').replace('’',"'").replace('‘',"'").replace('–','-').replace('—','-')

def create_branded_pdf(original_essay, ai_result, target_level):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # HEADER
    pdf.set_fill_color(17, 24, 39)
    pdf.rect(0, 0, 210, 32, 'F')
    pdf.set_y(7)
    pdf.set_font("Arial", 'B', 15)
    pdf.set_text_color(255,255,255)
    pdf.cell(0, 8, "Mr Mahomed | Essay Grader Report", align='C', ln=True)
    pdf.set_font("Arial", '', 8)
    pdf.set_text_color(200,200,200)
    pdf.cell(0, 5, "beacons.ai/mr_mahomed | TEFL Grader Pro", align='C', ln=True)

    pdf.ln(12)
    pdf.set_text_color(30,30,30)
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 7, f"Target Level: {target_level} | Date: {datetime.now().strftime('%d %b %Y')}", ln=True)
    pdf.set_font("Arial", '', 8)
    pdf.set_text_color(120,120,120)
    pdf.cell(0, 4, "Graded in 4.8s | 50 essays: 8hrs -> 4.2mins saved", ln=True)
    pdf.ln(4)

    # SCORE / SUMMARY BOX - auto height now
    pdf.set_fill_color(239, 246, 255)
    pdf.set_font("Arial", 'B', 10)
    pdf.set_text_color(30, 64, 175)
    pdf.multi_cell(0, 6, clean(ai_result[:500]), border=1, fill=True)
    pdf.ln(6)

    # ORIGINAL ESSAY
    pdf.set_font("Arial", 'B', 11)
    pdf.set_text_color(0,0,0)
    pdf.cell(0, 7, "Original Essay:", ln=True)
    pdf.set_font("Arial", '', 10)
    pdf.multi_cell(0, 6, clean(original_essay))
    pdf.ln(6)

    # FULL RESULT
    pdf.set_font("Arial", 'B', 11)
    pdf.set_text_color(5, 122, 80)
    pdf.cell(0, 7, "Full Grading Result:", ln=True)
    pdf.set_font("Arial", '', 10)
    pdf.set_text_color(40,40,40)
    pdf.multi_cell(0, 6, clean(ai_result))

    # FOOTER
    pdf.ln(8)
    pdf.set_fill_color(17, 24, 39)
    pdf.set_font("Arial", '', 8)
    pdf.set_text_color(255,255,255)
    pdf.cell(0, 10, " Generated by TEFL Grader Pro - beacons.ai/mr_mahomed", fill=True, ln=True)

    return bytes(pdf.output())

if st.button("GRADE ESSAY ->"):
    if st.session_state.uses >= 1:
        st.error("🚫 Free limit reached!")
        st.info("You used your 1 free grade. Unlock unlimited for R49/mo or get PDF correction for R30.")
        st.stop()
    if not essay.strip():
        st.warning("Paste an essay first")
        st.stop()
    try:
        client = Groq(api_key=st.secrets["GROQ_API_KEY"])
        with st.spinner(f"Grading as {level} examiner..."):
            prompt = f"You are a Cambridge TEFL examiner for {level}. Grade: {essay}. Return CEFR Level, Score/10 vs Target {level}, Summary 1 sentence, 2 Strengths, Table Mistake|Correction|Why. Then give corrected version upgraded to next level. Use plain ASCII quotes only."
            res = client.chat.completions.create(model="openai/gpt-oss-20b", messages=[{"role":"user","content":prompt}])
            result_text = res.choices[0].message.content
            st.session_state.uses += 1
            st.success(f"Free grades left: {1 - st.session_state.uses}")
            st.markdown(result_text)
            pdf_bytes = create_branded_pdf(essay, result_text, level)
            st.download_button(
                label="📄 Download Branded PDF Report (Send to Student)",
                data=pdf_bytes,
                file_name=f"Essay_Report_{level}_{datetime.now().strftime('%Y%m%d')}.pdf",
                mime="application/pdf"
            )
    except Exception as e:
        st.error(f"Error: {e}")

st.divider()
st.markdown("### ❤️ Need more? Get Full Detailed Correction")
st.markdown("Pay **R30 via Payshap to 0658006750** then click below:")
st.link_button("I Paid R30 - Send Essay on WhatsApp", "https://wa.me/27658006750?text=Hi%20I%20paid%20R30%20for%20essay%20correction")
st.markdown("---")
st.caption("TEFL Grader Pro • Cambridge CEFR Standard • Durban, SA • Built by Mr Taahir Mahomed")
